# Site settings
title: CICT Online
email: cict@wvsu.edu.ph
description: > # this means to ignore newlines until "baseurl:"
  College of Information and Communications Technology official website.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://cictwvsu.com" # the base hostname & protocol for your site
url: "http://127.0.0.1:8081" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
gems:
  - octopress-minify-html
exclude:
  - package.json
  - bower.json
  - node_modules
  - gulpfile.js
  - bower_components
  - cssjs_src
  - raw
  - tracer
